//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strategy.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Strategy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArmyBot1 {
            get {
                object obj = ResourceManager.GetObject("ArmyBot1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArmyBot2 {
            get {
                object obj = ResourceManager.GetObject("ArmyBot2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArmyBot3 {
            get {
                object obj = ResourceManager.GetObject("ArmyBot3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArmyBot4 {
            get {
                object obj = ResourceManager.GetObject("ArmyBot4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArmyBot5 {
            get {
                object obj = ResourceManager.GetObject("ArmyBot5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArmyPlayer1 {
            get {
                object obj = ResourceManager.GetObject("ArmyPlayer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [
        ///  [ 1, &quot;Town hall&quot;, 10, 2, 28, 200, 10 ],
        ///  [ 2, &quot;Houses&quot;, 25, 200, 5000, 10, 250, 150, 200, 10 ],
        ///  [ 3, &quot;Walls&quot;, 10, 1, 2, 5, 500 ],
        ///  [ 4, &quot;Temple&quot;, 10, 1, 3, 3, 1, 2, 5, 750 ],
        ///  [
        ///    5,
        ///    &quot;Barracks&quot;,
        ///    10,
        ///    [
        ///      {
        ///        &quot;Item1&quot;: &quot;&quot;,
        ///        &quot;Item2&quot;: 0
        ///      },
        ///      {
        ///        &quot;Item1&quot;: &quot;Shooter&quot;,
        ///        &quot;Item2&quot;: 1
        ///      },
        ///      {
        ///        &quot;Item1&quot;: &quot;Shooter&quot;,
        ///        &quot;Item2&quot;: 1
        ///      },
        ///      {
        ///        &quot;Item1&quot;: &quot;&quot;,
        ///        &quot;Item2&quot;: 0
        ///      },
        ///      {
        ///        &quot;It [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Buildes {
            get {
                return ResourceManager.GetString("Buildes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CastleBot1 {
            get {
                object obj = ResourceManager.GetObject("CastleBot1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CastleBot2 {
            get {
                object obj = ResourceManager.GetObject("CastleBot2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CastleBot3 {
            get {
                object obj = ResourceManager.GetObject("CastleBot3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CastleBot4 {
            get {
                object obj = ResourceManager.GetObject("CastleBot4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CastleBot5 {
            get {
                object obj = ResourceManager.GetObject("CastleBot5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CastlePlayer1 {
            get {
                object obj = ResourceManager.GetObject("CastlePlayer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Empty {
            get {
                object obj = ResourceManager.GetObject("Empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Fight {
            get {
                object obj = ResourceManager.GetObject("Fight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Guide {
            get {
                object obj = ResourceManager.GetObject("Guide", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [
        ///  {
        ///    &quot;Name&quot;: &quot;Recruit&quot;,
        ///    &quot;Protection&quot;: 2,
        ///    &quot;Attack&quot;: 2,
        ///    &quot;SpeedAndInitiative&quot;: 1,
        ///    &quot;TimePreparation&quot;: 1,
        ///    &quot;PriceCoins&quot;: 2,
        ///    &quot;PricePeople&quot;: 1,
        ///    &quot;Bilding&quot;: &quot;TownHall&quot;,
        ///    &quot;LevelBilding&quot;: 1,
        ///    &quot;Longdistance&quot;: false
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;Shooter&quot;,
        ///    &quot;Protection&quot;: 3,
        ///    &quot;Attack&quot;: 4,
        ///    &quot;SpeedAndInitiative&quot;: 3,
        ///    &quot;TimePreparation&quot;: 3,
        ///    &quot;PriceCoins&quot;: 8,
        ///    &quot;PricePeople&quot;: 1,
        ///    &quot;Bilding&quot;: &quot;Barracks&quot;,
        ///    &quot;LevelBilding&quot;: 1,
        ///    &quot;Longdistance&quot;: true
        ///  }, [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
    }
}
